# This workflow installs Maud on Ubuntu with Python 3.7 and then runs tox

name: Install Maud and run tox

on:
  push:
    branches:
      - 'main'
    tags:
      - '**'
  pull_request:
  workflow_dispatch: {}

env:
  CMDSTAN_VERSION: "2.33.1"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install cmdstanpy

    - name: CmdStan installation cacheing
      uses: actions/cache@v2
      with:
        path: ~/.cmdstan
        key: ${{ runner.os }}-cmdstan-${{ env.CMDSTAN_VERSION }}

    - name: Install cmdstan
      run: python -m cmdstanpy.install_cmdstan --version "${{ env.CMDSTAN_VERSION }}" --cores 2

    - name: Install Maud
      run: pip install .[development]

    - name: Run tox
      run: tox
