# This workflow installs Maud on Ubuntu with Python 3.7 and then runs integration tests

name: Run Maud integration tests

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Maud
      run: |
        python -m pip install --upgrade pip
        pip install .[development]
    - name: Install cmdstan
      run: install_cmdstan
    - name: Run integration tests
      run: pytest tests/test_integration

